
let
    txt = Text.Lower([Comment]),
    good = {"happy", "satisfied", "delicious", "amazing", "love", "excellent", "great", "enjoyed", "recommend", "best"},
    bad = {"disappointed", "bad", "terrible", "awful", "hate", "worst", "horrible", "disgusting", "not good", "dislike"},
    
    countGood = List.Count(List.Select(good, each Text.Contains(txt, _))),
    countBad = List.Count(List.Select(bad, each Text.Contains(txt, _))),
    
    result = if countGood > countBad then "Positive" 
             else if countBad > countGood then "Negative" 
             else "Neutral"
in
    result
------------------------------------------------------------------------------------

Home > New Source > Blank Query


let
    Source = CustomerFeedback, // ตรวจสอบว่าชื่อตารางหลักของคุณชื่อนี้
    AllComments = Text.Lower(Text.Combine(Source[Comment], " ")),
    GoodWords = {"happy", "satisfied", "delicious", "amazing", "love", "excellent", "great", "enjoyed", "recommend", "best"},
    BadWords = {"disappointed", "bad", "terrible", "awful", "hate", "worst", "horrible", "disgusting", "not good", "dislike"},
    
    FnCount = (w) => (Text.Length(AllComments) - Text.Length(Text.Replace(AllComments, w, ""))) / Text.Length(w),
    
    TableGood = Table.FromList(GoodWords, Splitter.SplitByNothing(), {"Word"}),
    AddGoodCount = Table.AddColumn(TableGood, "Count", each FnCount([Word])),
    AddGoodType = Table.AddColumn(AddGoodCount, "Category", each "Good"),
    
    TableBad = Table.FromList(BadWords, Splitter.SplitByNothing(), {"Word"}),
    AddBadCount = Table.AddColumn(TableBad, "Count", each FnCount([Word])),
    AddBadType = Table.AddColumn(AddBadCount, "Category", each "Bad"),
    
    Combined = Table.Combine({AddGoodType, AddBadType}),
    Final = Table.TransformColumnTypes(Combined,{{"Count", Int64.Type}})
in		
 	Final	
